### ISSUE TITLE
Running cudnn_samples_v7

### ISSUE THREAD

**Issue by ohcurrent** [gpgpu-sim/gpgpu-sim_distribution#100]
Hello I am using 'gpgpusim-dev ver.' and running 'cudnn_samples_v7/mnistCUDNN' I get this error message.

**_**_"CUDNN failure
 Error: CUDNN_STATUS_NOT_INITIALIZED"_**_**

My environment settings are like below.
_(Virtualbox)
Ubuntu 16.04.5 LTS
gcc 5.4.0 g++ 5.4.0
python 3.6.7
cuda 9.1
cudnn 7.0.5_

Does anyone know how to solve that error message?

**Comment by deval281shah** [comment]
Hello,
CuDNN is tested for the following configuration:

Ubuntu 16.04.5 LTS
gcc 5.4.0 g++ 5.4.0
CUDA 8.0
cuDNN 7.1.4
Please try with these settings.

Also, you can use mnist example code for GPGPU-Sim: https://github.com/gpgpu-sim/gpgpu-sim_simulations/tree/master/benchmarks/src/cuda/cudnn/mnist (It has detailed steps as well)

**Comment by ohcurrent** [comment]
Hello, thanks for the fast reply.

I have tried with your recommended environment settings with the link you referred.
However, I still did not get 'cudnn/mnistCUDNN' work to run.

I am facing this kind of error...
![image](https://user-images.githubusercontent.com/45330740/54082252-b5081e00-4355-11e9-8628-91ceb854590c.png)
Can you help me solve this out? :)

**Comment by deval281shah** [comment]
Hi,
Which config files (gpgpusim.config) are you using?

**Comment by ohcurrent** [comment]
I am using 'SM6_TITANX' config.

Thank you.

**Comment by deval281shah** [comment]
Hi,
Thanks for reporting the issue. This might be an issue is with the config file.
Have you tried with SM7_TITANV. It works for that config.

**Comment by ohcurrent** [comment]
Thank you for the help!
Now I got 'cudnn/mnist' working!


However, now I have trouble running 'pytorch_gpgpusim'.
When I execute pytorch example (https://github.com/pytorch/examples) 'examples/mnist', I think it is not running on GPGPU-Sim dev. branch...
![image](https://user-images.githubusercontent.com/45330740/54355295-0c7ef480-469c-11e9-9923-3ef7661f35f4.png)
When I do 'python setup.py install --user' at 'pytorch-gpgpu-sim', it prints out like
![image](https://user-images.githubusercontent.com/45330740/54354619-75656d00-469a-11e9-99e7-fc60e65adcb6.png)
for running the application in GPGPU-Sim, doesn't the cudart library path should be at where GPGPU-Sim is (~/gpgpu-sim_distribution-dev/lib/gcc-5.4.0/cuda-8000/release/libcudart.so.8.0)?

I executed the application as below,
(settings)
Ubuntu 16.04.6 LTS
gcc 5.4.0 g++ 5.4.0
CUDA 8.0
cuDNN 7.1.4
export PYTORCH_BIN=/usr/lib/x86_64-linux-gnu/libcudnn.so (->bashrc)
python 2.7
(steps)
source setup environment
make clean && make
copied the config(TITANV) at 'examples/mnist'
python setup.py install --user
pip install -r requirements.txt
python main.py

**Comment by shengyushen** [comment]
> Hi,
> Thanks for reporting the issue. This might be an issue is with the config file.
> Have you tried with SM7_TITANV. It works for that config.
but cuda8.0 dont support sm7, how an I use it?

**Comment by shengyushen** [comment]
but cuda 8.0 dont support sm7, how can I use it?
> Hi,
> Thanks for reporting the issue. This might be an issue is with the config file.
> Have you tried with SM7_TITANV. It works for that config.

**Comment by shengyushen** [comment]
cuda8.0 dont support tensorcore, wich need cuda9.0, so how to resolve this?

**Comment by gangmul12** [comment]
I think libcudart path on pytorch installation is not that important because gpgpu-sim is based on dynamic library hijacking. Just running pytorch is not working??

**Comment by ohcurrent** [comment]
Yes, I got GPGPU-Sim dev. to enable running cuDNN (cudnn_samples_v7/mnistCUDNN).
However, the 'pytorch_gpgpu-sim' does not work.
I tried pytorch 'examples/mnist' as I mentioned above, and got the result loke that.
Also, I've tried running pytorch 'examples/word_language_model', but I got error message like
_**'Error: libcaffe2.so: cannot open shared object file: No such file or directory.'**_

Did you get pytorch working on GPGPU-Sim?

**Comment by gangmul12** [comment]
I got stucked at another error message, but i think i am a few step ahead of you because gpgpusim is  successfully loaded when executing "python main.py" in examples/mnist.
How's the result when just launching python and execute import torch?

*my env
python 2.7.12
gcc 5.4
Ubuntu 16.04.06
CUDA 8.0
cudnn 7.1.4
gpgpu-sim commit 49e95cd

**Comment by ohcurrent** [comment]
What kind of error message are you at?

**Comment by gangmul12** [comment]
@ohcurrent 
i wrote issus #101 
![capture](https://user-images.githubusercontent.com/11365962/54835117-ddecc380-4d04-11e9-8fb4-64f1289c4a41.PNG)

I produced this message when i test resnet, and reproduced it when runnig examples/mnist

**Comment by ohcurrent** [comment]
For me the error is like this.
![image](https://user-images.githubusercontent.com/45330740/54843935-f2d35200-4d18-11e9-9aaf-56fc12f00a3d.png)

**Comment by gangmul12** [comment]
@ohcurrent
maybe you should set PYTORCH_BIN env variable as gpgpusim indicated

**Comment by ohcurrent** [comment]
After I did _**export PYTORCH_BIN=/usr/lib/x86_64-linux-gnu/libcudnn.so**_
I get
![image](https://user-images.githubusercontent.com/45330740/54875077-28705c00-4e3b-11e9-93f5-63a9bf4e5e01.png)

**Comment by gangmul12** [comment]
I think we are now in the same problem! However, attribute error seems like python error, not gpgpu-sim. i suggest you to test that your program works well without using gpgpu-sim.

**Comment by ohcurrent** [comment]
@gangmul12 Long time no see! 
Now I am working on this.
![image](https://user-images.githubusercontent.com/45330740/55287846-719b4f80-53e9-11e9-8bc8-c0d36a44ef3f.png)
Any progress after your issue?

**Comment by gangmul12** [comment]
Long time no see XD
No, currently i'm not working on this issue now.. Also i've never seen that issue, maybe your problem seems different from mine! However, again, isn't it python error? It doesn't seem like gpgpu-sim error...

**Comment by cng123** [comment]
Hi. This has been a known issue, and it has to do with kernels not being found in libcudnn.so. Please try the instructions in the link below and see if it helps.
https://docs.google.com/document/d/17fSM2vrWodP8rWR7ctpgaggVXEw0uD2VCAh0Gi4Gpb4/edit?usp=sharing

**Comment by ohcurrent** [comment]
@cng123 Did your method succeed in any cudaLaunch for PyTorch examples?

**Comment by cng123** [comment]
cudaLaunch succeeded for some of the PyTorch examples. However, the kernels might still fail (cuda_status_internal_errror.) Unfortunately, I have not resolved this issue yet.

**Comment by ohcurrent** [comment]
@cng123 Thank you for sharing the link.
However, how do you know 'np PTX implementation~' error is related with wrong cuDNN paths?

**Comment by cng123** [comment]
@ohcurrent It was just based on personal experience with experimenting with different builds with different environmental variables. There are probably other problems that may lead to the same error, but the most common one I have seen so far is with the wrong (or unset) cuDNN paths.

It seems like if the caffe shared library is not statically linked to cudnn (so either dynamically linked, or not linked at all,) the 'no PTX implementation' will occur, which is a problem since it means that if pytorch is not built with cudnn and only with cuda, it will not work with gpgpu-sim. I am speculating that it has to do with libcublas and other cuda libraries being dynamically linked, but I cannot say for sure.

**Comment by ohcurrent** [comment]
@cng123 I see... thank you for sharing your experience.
As I struggle at 'no PTX implementation', it really helps!

**Comment by ohcurrent** [comment]
@cng123 Hi!
Did you succeed in simulating any of the 'PyTorch/examples' with dev without errors?
Thank you.

**Comment by mivenHan** [comment]
@ohcurrent Have you solved cudnn error with mnistCudnn? I encountered the same error with you.

**Comment by ohcurrent** [comment]
@mivenHan 
 Yes, you can just edit the  Makefile of the mnistCudnn, as below.
The application should be compiled with static libraries

#LIBRARIES += -LFreeImage/lib/$(TARGET_OS)/$(TARGET_ARCH) -LFreeImage/lib/$(TARGET_OS) -lcudart -lcublas -lcudnn -lfreeimage -lstdc++ -lm

LIBRARIES += -LFreeImage/lib/$(TARGET_OS)/$(TARGET_ARCH) -LFreeImage/lib/$(TARGET_OS) -lcudart -lcublas_static -lcudnn_static_v7 -lculibos -lfreeimage -lstdc++ -lm -ldl -lpthread

**Comment by mivenHan** [comment]
@ohcurrent Thank you for your reply first.

I want to confirm that you did complete the mnistCUDNN successfully under the cuda 9.1?
Since I worked with mnist example code for GPGPU-Sim: [https://github.com/gpgpu-sim/gpgpu-sim_simulations/tree/master/benchmarks/src/cuda/cudnn/mnist](url)

My cuda version is 9.0
and I try the cudnn 7.6.5 and cudnn 7.1.4 and cudnn 7.0.5.

All failed with a new error.

```
GPGPU-Sim PTX: WARNING: Asynchronous memset not supported (cudaError_t cudaMemsetAsync(void*, int, size_t, cudaStream_t))
./mnistCUDNN: relocation error: ./mnistCUDNN: symbol cudaFuncSetAttribute, version libcudart.so.9.0 not defined in file libcudart.so.9.0 with link time reference
```
Have you encountered that error?
Or the code with cuda 9.1 and cudnn 7.0.5 can complete running successfully?

Thank you for your time.
