### ISSUE TITLE
not able to run pytorch-kernel

### ISSUE THREAD

**Issue by gangmul12** [gpgpu-sim/gpgpu-sim_distribution#101]
I tried to run pytorch with gpgpusim-dev, but i found that gpgpu-sim are not able to register cuda kernels in pytorch(like kernelPointwiseApply1 in aten/src/THC/THCApply.cuh).
Does anyone know that it is intended result of author or it is just my fault!

Thank you

Used env:
Ubuntu 16.04.6
gcc&g++ 5.4.0
CUDA 8.0
cuDNN 7.1.4

**Comment by RedCarrottt** [comment]
Hello, I have similar problem with you. (Issue #110)
Could you tell me which line of ```TCHApply.cuh``` makes the problem, exactly?

Thank you.

**Comment by gangmul12** [comment]
Hi, I think your problem is different from my error. my error occurs from gpgpu-sim, not pytorch. cudaGetDeviceCount is a basic api defined in gpgpu-sim/libcuda/cuda_runtime_api.cc, so you should run it without any problem.
https://github.com/gpgpu-sim/gpgpu-sim_distribution/blob/7cd0edfe0cb654280c30afef89a563867d9e67ed/libcuda/cuda_runtime_api.cc#L748

I think gpgpu-sim library link is failed in your environment....

**Comment by RedCarrottt** [comment]
Yes, it was a problem related to library linking. After I set several environment values, it works well.
Thank you.

**Comment by cng123** [comment]
Hi. This has been a known issue, and it has to do with kernels not being found in libcudnn.so. Please try the instructions in the link below and see if it helps.
https://docs.google.com/document/d/17fSM2vrWodP8rWR7ctpgaggVXEw0uD2VCAh0Gi4Gpb4/edit?usp=sharing

**Comment by gangmul12** [comment]
@cng123 Thank you for sharing comment! I didn't try it yet and i will report the result after trial.. However, I have question. It seems it uses static CuDNN library. Then, did you build the cudnn as a static library not a shared library?

**Comment by cng123** [comment]
I am not sure what you mean by build cudnn as a static library, since I downloaded the static and shared library "as is" from Nvidia's website.

**Comment by gangmul12** [comment]
Aha, i forgot that there is official static library from Nvidia. Thank you for the precious comment!
