### ISSUE TITLE
pytorch-gpgpu-sim "PYTORCH_BIN"

### ISSUE THREAD

**Issue by ohcurrent** [gpgpu-sim/gpgpu-sim_distribution#107]
Hello, I am trying to simulate pytorch-gpgpu-sim with gpgpu-sim.dev.

Before, I have tried running cudnn_samples_v7/mnistCUDNN.
Without static linking it does not run, as you mentioned in the paper(Analyzing Machine Learning Workloads Using a Detailed GPU Simulator). Therefore, I added  "static linking of cublas and cudnn"in the makefile, and this made it run successfully.

However, on README of pytorch_gpgpusim, it says "export PYTORCH_BIN=/path/to/libcudnn.so", which I think it is doing dynamic linking with cudnn.
Is it true that pytorch use that "PYTORCH_BIN" path?
Is it right to dynamic link the cudnn when using PyTorch?

Thank you.

(My env.)
Ubuntu 16.04.5 LTS
gcc 5.4.0 g++ 5.4.0
Python 2.7
CUDA 8.0
cuDNN 7.1.4

**Comment by RedCarrottt** [comment]
I also wonder what PYTORCH_BIN exactly means.
I tried to find out where PYTORCH_BIN is required, but I could not find that.

**Comment by RedCarrottt** [comment]
Hello,
As I know, libcuda in gpgpu-sim uses the ```PYTORCH_BIN``` variable to extract ptx code.
Therefore, you can set the variable as existing ```libcudnn.so``` file (downloaded from Nvidia web site and installed).

**Comment by ohcurrent** [comment]
Hmm... I see, thank you for the comment!

Anyway, I am facing this kind of error message, right now.

_**GPGPU-Sim API: Stream Manager State
GPGPU-Sim: detected inactive GPU simulation thread
NVIDIA: no NVIDIA deviced found
RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED**_

I think this message is printed out after PTX is all loaded to GPGPU-Sim, and getting ready to launch the application...

Do you have any idea what the problem is?
Did you succeed in running pytorch_gpgpusim on GPGPU-Sim dev?

**Comment by RedCarrottt** [comment]
Not yet. I'm facing another problem to run the pytorch-gpgpu-sim.
Your problem may be the next step of my situation...

**Comment by RedCarrottt** [comment]
Hello, did you solve this issue?
After I solve Issue #111, I've met similar issue with you.

I set several environment values as following.
```
PYTORCH_BIN=/usr/local/cuda/lib64/libcudnn.so
LD_LIBRARY_PATH=/home/ubuntu/gpgpu-sim_distribution/lib/gcc-5.4.0/cuda-8000/release/:/usr/local/cuda/lib64
```

And I removed my original ```libcudart.so``` from ```/usr/local/cuda/lib64``` directory and replace it with my ```libcudart.so``` (the result library file of gpgpu-sim_distribution).

However, when I run my pytorch model code(written in python, including only one convolution layer), I met following message.

```GPGPU-Sim API: Stream Manager State
GPGPU-Sim: detected inactive GPU simulation thread
GPGPU-Sim: synchronize waiting for inactive GPU simulation
GPGPU-Sim API: Stream Manager State
GPGPU-Sim: detected inactive GPU simulation thread
Done my python code
GPGPU-Sim: *** exit detected ***
```

I could not met ```no NVIDIA deviced found``` nor ```CuDNN error: CUDNN_STATUS_NOT_INITIALIZED```, but any ```cudaLaunch()``` callback in GPGPU-Sim is not executed.

I guess that dynamically-linked ```libcudnn.so``` does not call ```libcudart.so``` with GPGPU-Sim, but it calls original ```libcudart.so```...

**Comment by ohcurrent** [comment]
> Hello, I am trying to simulate pytorch-gpgpu-sim with gpgpu-sim.dev.
> 
> Before, I have tried running cudnn_samples_v7/mnistCUDNN.
> Without static linking it does not run, as you mentioned in the paper(Analyzing Machine Learning Workloads Using a Detailed GPU Simulator). Therefore, I added "static linking of cublas and cudnn"in the makefile, and this made it run successfully.
> 
> However, on README of pytorch_gpgpusim, it says "export PYTORCH_BIN=/path/to/libcudnn.so", which I think it is doing dynamic linking with cudnn.
> Is it true that pytorch use that "PYTORCH_BIN" path?
> Is it right to dynamic link the cudnn when using PyTorch?
> 
> Thank you.
> 
> (My env.)
> Ubuntu 16.04.5 LTS
> gcc 5.4.0 g++ 5.4.0
> Python 2.7
> CUDA 8.0
> cuDNN 7.1.4
