### ISSUE TITLE
Flushing dirty L2 cache lines does not generate DRAM writes

### ISSUE THREAD

**Issue by SerinaTan** [gpgpu-sim/gpgpu-sim_distribution#151]
I am curious why generating DRAM write requests for dirty lines is left as a TODO item in the flushL2() function? https://github.com/gpgpu-sim/gpgpu-sim_distribution/blob/dev/src/gpgpu-sim/l2cache.cc#L581

Are there any non-trivial technical difficulties involved or is it just a matter of extra engineering efforts? Unless someone is currently looking into it, I would be happy to take a crack at it.

**Comment by mkhairy** [comment]
Hi Serina, No need to flush. This is just an old comment which we forgot to remove.
All the requests from the GPU cores and CPU memory copies go to the L2 cache memory before the DRAM.

**Comment by SerinaTan** [comment]
Hi Mahmoud, thanks for your clarification! I didn't know about this L2 cache behavior before. No wonder the "gpgpu_flush_l2_cache" flag is off for Volta then.

For anyone else who is curious: https://devtalk.nvidia.com/default/topic/936462/cudamemcpy-and-l2-cache-/

Closing this issue.
