### ISSUE TITLE
Do I need to install nvidia-driver?

### ISSUE THREAD

**Issue by theverytak** [gpgpu-sim/gpgpu-sim_distribution#158]
Hi, I'm recently trying to use dev branch version of gpgpu-sim(currently using old gpgpu-sim). I compiled it with cuda 8.0 version and tried to test if it works by running a benchmark from Rodinia 3.1 Benchmark suite. But it stopped right after the configuration was finished. I checked the msg and it says my cuda version is not compatible with my nvidia driver version.

Seems like I need to install nvidia-driver to use GPGPUSim, so my question is:
1. Do I need to install nvidia-driver that has compatibility with my cuda version to use dev branch GPGPUSim?
2. If so, is it possible to install nvidia-driver without having a solid graphics card?

Thanks for your help in advance.

**Comment by theverytak** [comment]
It was such a stupid question. Close it by myself 😞

**Comment by debtanu09** [comment]
Hey can you explain me the solution, I'm still confused
