### ISSUE TITLE
It seems that GPGPU-sim DRAM does not consider RAW dependency when using separate R/W queue

### ISSUE THREAD

**Issue by allencho1222** [gpgpu-sim/gpgpu-sim_distribution#174]
As the subject described, when GPGPU-sim uses separate Read and Write queue, it does not consider RAW dependency.

For example, if the Write request (Address A) arrived at the Write queue in DRAM, the Read request (Address A) targeting same address might arrive. Assuming this situation, due to watermark policy in DRAM, the Read request (Address A) can be scheduled before the Write request (Address A)  is scheduled.

I want to know why it is not considered. If I am missing something, can somebody give comments?

**Comment by RSpliet** [comment]
Are these requests coming from the same warp? If so, I suspect the caches should resolve this and the read should never hit DRAM in the first place. If you're talking about hazards between different warps, NVIDIA hardware does not enforce any read/write ordering without explicit barriers, and explicit barriers only allow ordering within the same CTA/work-group up until (I think) NVIDIA's Maxwell GPUs.

**Comment by allencho1222** [comment]
@RSpliet Thank you for your answer. First of all, the question was just assumption, not based on the experiment. I know the fact that NVIDIA GPU does not consider memory consistency between different shader cores. I thought that cache thrasing in L1D cache might cause such issues assuming L2 miss occurs. However, I think I need to take a careful look at the source code again whether these are handled or not.
