### ISSUE TITLE
cudaMallocManaged returns with error

### ISSUE THREAD

**Issue by topcuburak** [gpgpu-sim/gpgpu-sim_distribution#252]
Hi, 

I am trying to execute [Altis](https://github.com/utcs-scea/altis) benchmark in GPGPU-Sim. I have configured the related CMake files such that the -lcudart flag is set and CUDA codes would be executed on the simulator. However, it returns the following error:
**symbol cudaMallocManaged version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference** 
I have also tried a simple code to realize the related problem with the attached CUDA code, and the similar problem still exists. I checked .so files in de CUDA directory to see whether cudaMallocManaged is implemented or not, and it can find this function. However, the created .so objects in the lib/gcc**/release/libcudart**.so do not implement this function after I rebuilt the simulator.  

Do you have any idea?
Best regards,
 - My workstation works with ubuntu 18.04 LTS, CUDA-11.4, and GCC 7.5. 

[cudamallocmanaged.zip](https://github.com/gpgpu-sim/gpgpu-sim_distribution/files/8402995/cudamallocmanaged.zip)

**Comment by yuechen-sys** [comment]
I account this problem months ago. Altis benchmark is using UVM feature but GPGPU-Sim 4.0 not include, sin cudaMallocManaged not implemented in GPGPU-SIm

**Comment by topcuburak** [comment]
Wow. Thank you.

**Comment by topcuburak** [comment]
Wow. Thank you.

**Comment by NikhilMolugu** [comment]
You can check for UVMSmart by Debashish Ganguly. It is GPGPU-Sim v3 + UVM and is publicly available on his github. cudaMallocManaged is supported in that simulator. That work is part of the research paper "Interplay between Hardware Prefetcher and Page Eviction Policy in CPU-GPU Unified Virtual Memory".

If you want UVM on GPGPU-Sim v4, I will be making a public repository in a few months when I publish my work.
