### ISSUE TITLE
Makefile.makedepend no such file

### ISSUE THREAD

**Issue by mahmoodn** [gpgpu-sim/gpgpu-sim_distribution#44]
while sourcing **setup_environment** was successful, I get an error that can not find **uda-sim/Makefile.makedepend**

`mahmood@vb:~/gpgpu-sim_distribution$ make

        Building GPGPU-Sim version 3.2.2 (build ) with CUDA version 4.2

if [ ! -d lib/gcc-4.6.3/cuda-4020/release ]; then mkdir -p lib/gcc-4.6.3/cuda-4020/release; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libcuda ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libcuda; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/decuda_pred_table ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/decuda_pred_table; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpgpu-sim ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpgpu-sim; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libopencl ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libopencl; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libopencl/bin ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/libopencl/bin; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/intersim2 ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/intersim2; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuobjdump_to_ptxplus ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuobjdump_to_ptxplus; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpuwattch ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpuwattch; fi;
if [ ! -d /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpuwattch/cacti ]; then mkdir -p /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/gpuwattch/cacti; fi;
make -C ./src/cuda-sim/ depend
make[1]: Entering directory `/home/mahmood/gpgpu-sim_distribution/src/cuda-sim'
Makefile:149: /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/Makefile.makedepend: No such file or directory
touch /home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/Makefile.makedepend
makedepend -f/home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/Makefile.makedepend -p/home/mahmood/gpgpu-sim_distribution/build/gcc-4.6.3/cuda-4020/release/cuda-sim/ cuda_device_printf.cc cuda-sim.cc instructions.cc memory.cc ptx_ir.cc ptx_loader.cc ptx_parser.cc ptx_sim.cc ptx-stats.cc 2> /dev/null
make[1]: *** [depend] Error 127
make[1]: Leaving directory `/home/mahmood/gpgpu-sim_distribution/src/cuda-sim'
make: *** [cuda-sim] Error 2
`

**Comment by tgrogers** [comment]
which branch is this on?

**Comment by mahmoodn** [comment]
I am using ubuntu 13.04 which uses gcc-4.6
Anyway, I installed xutils-dev and the error has been fixed.

**Comment by tgrogers** [comment]
right - by branch I meant dev or release.
It's possible you did not have makedepend installed - ideally setup_environment would test for this.

**Comment by mahmoodn** [comment]
As an update for anyone in the future, in Centos, the package for that is called **imake**

**Comment by FlashBarryAllen** [comment]
how about redhat8? I can't find the makedepend either.
