### ISSUE TITLE
DNN workloads

### ISSUE THREAD

**Issue by mahmoodn** [gpgpu-sim/gpgpu-sim_distribution#47]
Is it possible to simulate DNN workloads with the dev branch? Has anyone tried that?

**Comment by abhi1212** [comment]
If you are talking about Deep Neural Nets, which library you are planning to use?

**Comment by mahmoodn** [comment]
How about [DeepBench](https://github.com/baidu-research/DeepBench) which uses cuDNN and OpenMPI.

**Comment by abhi1212** [comment]
Libraries like cuDNN comes directly with binaries, so you cannot run them on gpgpu sim.

**Comment by mahmoodn** [comment]
As you know, most of the DNNs use that library. What you said means we have to ignore them. 
I was looking at the nvidia [catalog](http://www.nvidia.com/content/gpu-applications/PDF/gpu-applications-catalog.pdf) which lists a large set of modern applications. I was planning to use gpgpusim with newer workloads rather than old ones which are broadly discovered wince 2009.
What about applications which use [TensorFlow](https://github.com/tensorflow)?
What about [Caffe](https://github.com/BVLC/caffe)?

**Comment by abhi1212** [comment]
Bothe Caffe and Tensor flow use Cudnn or Cublas library.

**Comment by mahmoodn** [comment]
So may I ask which application is cadidate for gpgpusim?
By now, all applications that use cuDNN and cuBLAS should be ignored.

**Comment by mattsinc** [comment]
None of the applications that use special libraries like cuDNN or cuBLAS can run on GPGPU-Sim at this point.  This includes all of the applications/frameworks you mentioned above.  Basically, GPGPU-Sim needs to have the source code to execute the GPU kernels.  So any benchmark that is self-contained should work.  Applications that can run include those from Rodinia, Parboil, MARS, Pannotia, GPGPU-Sim, GPU TM, Lonestar (although Lonestar needs to extra hacks to get it to work), etc.

Matt

**Comment by mahmoodn** [comment]
Please take a time and have a look at the following projects. Let me know if you think it is worth to work with them for gpgpusim

BIDMach
https://github.com/BIDData/BIDMach

blazegraph
https://github.com/blazegraph

Deepgram
https://github.com/deepgram/kur

Graphistry
https://github.com/graphistry

Gunrock
https://github.com/gunrock/gunrock
Installation is here http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html

**Comment by mahmoodn** [comment]
The second and final set of applications

h2oai
https://github.com/h2oai/h2o-3

MatConvNet
https://github.com/vlfeat/matconvnet
This uses Matlab and cuDNN is optional

DualSPHysics
http://www.dual.sphysics.org/index.php/downloads/

HiFiLES
https://github.com/HiFiLES/HiFiLES-solver
This is a good one

PyFR
https://github.com/vincentlab/PyFR
http://www.pyfr.org/download.php
This is a good one

BarraCUDA 
http://seqbarracuda.sourceforge.net/
This is good

Arioc
https://github.com/RWilton/Arioc

PEANUT 
http://peanut.readthedocs.io/

RELION
https://www2.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install

UGene
http://ugene.net/download.html

Quantum ESPRESSO
http://www.quantum-espresso.org/download/

GROMACS
http://www.gromacs.org/GPU_acceleration

QMCPACK
http://qmcpack.org/

ArrayFire
https://github.com/arrayfire/arrayfire

Chroma
https://jeffersonlab.github.io/chroma/

3D Slicer
http://download.slicer.org/

GVDB
https://github.com/NVIDIA/gvdb-voxels
Is OptiX OK?

Seg3D
https://github.com/SCIInstitute/Seg3D/releases

VISIT
https://www.visitusers.org/index.php?title=Main_Page

OpenALPR
https://github.com/openalpr/openalpr


P.S:
I looked at nearly all applications in the nvidia catalog. Please note that:
- Most of the financial applications are not open source! 
- Most of the learning applications use cuDNN!
- Most of the engineering (CAD/CFD/...) applications are private!
- Most of the visual and image processing tools and rederers are not open source!
- There are some research engineering applications.
- Some Bioinformatic and Quantum tools are free and open source fortunately.
- Some safety and security applications are open source, e.g. car plate reading.


I would like to hear comments from you in order to know which applications are good for extending the current benchmark for gpgpusim.

**Comment by mattsinc** [comment]
Just since there are some blog posts that point to this issue as evidence that GPGPU-Sim does not support ML workloads, I wanted to make sure to update this issue/post to make it clear that the updated version of GPGPU-Sim now supports some ML workloads (including ones written in Python).  See the updated README for more details.

Matt
