### ISSUE TITLE
Compilation issue with solution

### ISSUE THREAD

**Issue by mahmoodn** [gpgpu-sim/gpgpu-sim_distribution#48]
While testing the dev branch with 
   ubuntu 16.04
   gcc/g++ 4.8
   cuda 7.5

In case of **error: ‘isnan’ was not declared in this scope**, just use **std::isnan** or add **using namespace std;** at the top of the problematic file

**Comment by abhi1212** [comment]
Well there is a patch for that, [(https://groups.google.com/forum/#!topic/gem5-gpu-dev/VT_nHBCK8Qg)]
Check this link, you need to download the patch and also need to do some small changes in some files and it works.
