### ISSUE TITLE
Formatting warnings of printf

### ISSUE THREAD

**Issue by mahmoodn** [gpgpu-sim/gpgpu-sim_distribution#49]
With the following specs
    ubuntu 16.04
    cuda 7.5
    gcc/g++ 4.8

there are some warnings in **ptx_parser.cc** such as this

```
ptx_parser.cc:438:41: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘new_addr_type {aka long long unsigned int}’ [-Wformat=]
               addr+addr_pad + num_bits/8);

```
That line of code is

```
printf("from 0x%x to 0x%lx (global memory space) %u\n",   
                    addr+addr_pad,    
                    addr+addr_pad + num_bits/8,
                    g_const_alloc++);

```
The data types are 
```
   size_t num_bits;
   unsigned addr_pad;
   new_addr_type addr;
```
and the last one is actually **unsigned long long**. So, I think the correct format is **%llx** for all of the statements that use **addr**.

**Comment by tgrogers** [comment]
yup - there are lots of these type of warning in GPGPU-Sim.
If you fix them, create a PR and we will integrate it :)
