### ISSUE TITLE
gpgpusim has been built but unable to run a cuda application

### ISSUE THREAD

**Issue by mahmoodn** [gpgpu-sim/gpgpu-sim_distribution#52]
In the Dev branch it is stated that after building gpgpusim, it is possible to run cuda based applications by chnaging the cuda library paths to gpgusim library folder. Also, the GPU config file should be in the working directory.

Well, I did that but the application says no cuda device found! I also ran deviceQuery and it also said there is no cuda. 

```
mahmood@u1604:~/gpgpu-sim_distribution$ echo $LD_LIBRARY_PATH

mahmood@u1604:~/gpgpu-sim_distribution$ source setup_environment release
GPGPU-Sim version 3.2.2 (build ) WARNING ** GPGPU-Sim version 3.2.2 not fully tested with CUDA version 7.5 (please see README)
configured with GPUWattch.
setup_environment succeeded
mahmood@u1604:~/gpgpu-sim_distribution$ echo $LD_LIBRARY_PATH
/home/mahmood/gpgpu-sim_distribution/lib/gcc-4.8.5/cuda-7050/release:
mahmood@u1604:~/gpgpu-sim_distribution$ ls /home/mahmood/gpgpu-sim_distribution/lib/gcc-4.8.5/cuda-7050/release
libcudart.so    libcudart.so.4    libcudart.so.6.0  libcudart.so.8.0
libcudart.so.2  libcudart.so.5.0  libcudart.so.6.5
libcudart.so.3  libcudart.so.5.5  libcudart.so.7.5
mahmood@u1604:~/gunrock/build/bin$ ls
bc   chesapeake.mtx            hits   shared_lib_bc   shared_lib_example  sssp
bfs  config_quadro_islip.icnt  pr     shared_lib_bfs  shared_lib_pr       topk
cc   gpgpusim.config           salsa  shared_lib_cc   shared_lib_sssp     wtf
mahmood@u1604:~/gunrock/build/bin$ ./bfs market chesapeake.mtx --src=0 --unidirected
Loading Matrix-market coordinate-formatted graph ...
Reading from chesapeake.mtx:
  Parsing MARKET COO format (39 nodes, 340 directed edges)... Done parsing (0s).
  Converting 39 vertices, 340 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (39 vertices, 340 edges):
    Degree   0: 0 (0.00%)
    Degree 2^0: 0 (0.00%)
    Degree 2^1: 1 (2.56%)
    Degree 2^2: 22 (56.41%)
    Degree 2^3: 13 (33.33%)
    Degree 2^4: 2 (5.13%)
    Degree 2^5: 1 (2.56%)

  Converting 39 vertices, 340 directed edges (unordered tuples) to CSR format...
Done converting (0s).
Source vertex: 0
Using 1 GPU: [ 0 ].
[/home/mahmood/gunrock/gunrock/util/info.cuh, 470 @ gpu 32764] cudaGetDevice failed (CUDA error 38: no CUDA-capable device is detected)
[/home/mahmood/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 0] cudaSetDevice failed. (CUDA error 38: no CUDA-capable device is detected)
[/home/mahmood/gunrock/gunrock/util/info.cuh, 484 @ gpu 0] cudaStreamCreate failed. (CUDA error 38: no CUDA-capable device is detected)
CODE REQUESTED INVALID CUDA DEVICE -2050039464
mahmood@u1604:~/NVIDIA_CUDA-7.5_Samples/1_Utilities/deviceQuery$ make
"/usr/local/cuda-7.5"/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o deviceQuery.o -c deviceQuery.cpp
"/usr/local/cuda-7.5"/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o deviceQuery deviceQuery.o 
mkdir -p ../../bin/x86_64/linux/release
cp deviceQuery ../../bin/x86_64/linux/release
mahmood@u1604:~/NVIDIA_CUDA-7.5_Samples/1_Utilities/deviceQuery$ ../../bin/x86_64/linux/release/deviceQuery 
../../bin/x86_64/linux/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL

```

So, what should I do now?

**Comment by akj10** [comment]
Try commenting out cudaGetDevice, cudaSetDevice, cudaStreamCreate calls from the app?
If you try the BFS from Rodinia 3.1, it works.

**Comment by mahmoodn** [comment]
Actually, it is more than simple device checking. Looking at part of the init process ([here](https://github.com/gunrock/gunrock/blob/master/gunrock/util/info.cuh#L456)), such device information are used to determine the streams and other thing to  run on gpu.

Isn't possible for gpgpusim to return a device for cudaGetDevice()?

**Comment by topcuburak** [comment]
Hello Mahmood, 

Could you run the deviceQuery for the GPGPU-sim 3.0 or 4.0 to get the properties of the simulator? If you could (I hope so), can you share with me? I cannot go beyond the below log. Best wishes. 

./deviceQuery Starting...

CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 100
-> no CUDA-capable device is detected
Result = FAIL

**Comment by onnx-bsd** [comment]
Hi topcuburak

I am also facing same problem. All application compiling but while running it is not finding any CUDA enabled device.

**Comment by mahmoodn** [comment]
The topic is old, really. I suggest you to test the latest version.

**Comment by debtanu09** [comment]
Hi I'm getting the output-

Iterate 10 times with GPU 0 or CPU 1: 0
test 4 
ERROR: no CUDA-capable device is detected

I'm a absolute beginner in CUDA and GPGPU-SIM (started yesterday)
Can someone please help.

I'm trying the following code -
#include <cuda_runtime.h>
#include <cuda.h>
#include <stdio.h>
#include <sys/time.h>
#include <math.h>

#define N 32

__global__ void Kernel_double(int niters, int* d_inputs,double* d_outputs)
{
    int tid = blockIdx.x * blockDim.x + threadIdx.x;

    if (tid<N) {
    double val =(double) d_inputs[tid];
    /*for (int iter=0; iter < niters; iter++){
    val = (sqrt(pow(val,2.0)) + 5.0) - 101.0;
    val = (val / 3.0) + 102.0;
    val = (val + 1.07) - 103.0;
    val = (val / 1.037) + 104.0;
    val = (val + 3.00) - 105.0;
    val = (val / 0.22) + 106.0;
    }*/
    val = val + 1.0;
    //printf("This is %f\n",val);
    d_outputs[tid] = val;
}
}

int main(int argc, char **argv)
{

    int niters = 10;
    int cpu = 0;
    printf("Iterate %d times with GPU 0 or CPU 1: %d\n", niters, cpu);

    int inputs[N];
    for (int i = 0; i<N; i++){
    inputs[i] = i+1;
    }

    int *d_inputs;
    double *d_outputs;
    double outputs[N];

    cudaMalloc( (void**)&d_inputs, N*sizeof(int));
    cudaMalloc( (void**)&d_outputs, N*sizeof(double));
    printf("test %d \n", inputs[3]);
    cudaMemcpy(d_inputs, inputs, N*sizeof(int), cudaMemcpyHostToDevice);
//    printf("test %d \n", d_inputs[1]);
    Kernel_double<<<16,2>>>(niters, d_inputs,d_outputs);
    cudaDeviceSynchronize();
    cudaError_t error = cudaGetLastError();
    if(error!=cudaSuccess)
    {
      fprintf(stderr,"ERROR: %s\n", cudaGetErrorString(error) );
      exit(-1);
    }
    //cudaDeviceSynchronize();
    cudaMemcpy(outputs, d_outputs, N*sizeof(double), cudaMemcpyDeviceToHost);
    for(int j =0;j<10; j++){
        printf("Outputs[%d] is: %f\n",j, outputs[j]);
        }
    cudaFree(d_inputs);
    cudaFree(d_outputs);

    return EXIT_SUCCESS;
}

I have nvcc 11.2
gcc 10.2
I'm using the latest GPGPU Sim

**Comment by Tridu33** [comment]
same problem in 2025 master branch newest code
