### ISSUE TITLE
runtime error: "ImportError: /usr/local/cuda/lib64/libcublas.so.4: undefined symbol: cudaMemsetAsync"

### ISSUE THREAD

**Issue by libingict** [gpgpu-sim/gpgpu-sim_distribution#57]
Hi, all,
I am a new CNN learning and trying run cuda-convnet on gpgpu-sim_distribution simulator.
Cuda-convnet can run well on my server, but when I run cuda-convnet with the gpgpusim simulator, an error happenes. The error is "ImportError: /usr/local/cuda/lib64/libcublas.so.4: undefined symbol: cudaMemsetAsync". 
The details are like this:

> Importing _ConvNet C++ module
> Traceback (most recent call last):
> File "convnet.py", line 203, in 
> model = ConvNet(op, load_dic)
> File "convnet.py", line 43, in init
> IGPUModel.init(self, "ConvNet", op, load_dic, filename_options, dp_params=dp_params)
> File "/root/convnet/trunk/gpumodel.py", line 88, in init
> self.import_model()
> File "convnet.py", line 49, in import_model
> self.libmodel = import(lib_name)
> ImportError: /usr/local/cuda/lib64/libcublas.so.4: undefined symbol: cudaMemsetAsync

The wired thing is Cuda-convnet can run well on my server. After I change my $PATH and $LD_LIBRARY_PATH to the original value, the error disappears.
I setup my gpgpusim simulator following the tutorial and copy the config files into the convnet's work path.

I build the gpgpusim with gcc-5.4.1. The GPU config chose GTX480.
My cuda version is 4.0.
Here is the output of my libcublas.so
`nm -D /usr/local/cuda/lib64/libcublas.so |grep ‘cuda’`
>              U __cudaRegisterFatBinary
>              U __cudaRegisterFunction
>              U __cudaRegisterTexture
>              U __cudaUnregisterFatBinary
>              U cudaBindTexture
>              U cudaConfigureCall
>              U cudaCreateChannelDesc
>              U cudaEventCreateWithFlags
>              U cudaEventDestroy
>              U cudaEventQuery
>              U cudaEventRecord
>              U cudaEventSynchronize
>              U cudaFree
>              U cudaFuncGetAttributes
>              U cudaGetDevice
>              U cudaGetDeviceProperties
>              U cudaGetExportTable
>              U cudaGetLastError
>              U cudaLaunch
>              U cudaMalloc
>              U cudaMemcpy
>              U cudaMemcpy2D
>              U cudaMemcpy2DAsync
>              U cudaMemcpyAsync
>              U cudaMemsetAsync
>              U cudaSetupArgument
>              U cudaThreadSynchronize
>              U cudaUnbindTexture

`ll /usr/local/cuda/lib64/libcublas.so`

> lrwxrwxrwx 1 root root 14 Mar 17 16:10 /usr/local/cuda/lib64/libcublas.so -> libcublas.so.4*

Anyone know the reason for this error and how to fix it? Could anyone help me out with this issue? Thanks a lot in advance!

**Comment by mattsinc** [comment]
Currently GPGPU-Sim does not support cuBLAS, which it looks like are needed by your application.  In part, this is because GPGPU-Sim needs the source code for the kernels it is trying to run, and cuBLAS is closed source.

Matt

**Comment by libingict** [comment]
Hi, Matt,
Thanks so much. I read one previous [discussion.](https://github.com/gpgpu-sim/gpgpu-sim_distribution/issues/52) 
Gpugpusim does not support cuDNN and cuBlas. My new question is if it supports HDF5 library?
Thanks a lot.

**Comment by mattsinc** [comment]
As far as I know, the HDF5 library does not execute GPU code.  Thus, GPGPU-Sim should be unaffected by it.

Matt

**Comment by Sungwoo-Ahn** [comment]
@mattsinc Hi, Matt.
I was working on cublas code on gpgpu simulator but it didn't worked. It has problems with .so files.
Is GPGPU-Sim still does not support cublas library?

**Comment by mattsinc** [comment]
The recent updates on the dev branch should theoretically support cuBLAS, although I have not tried it and thus can't say for sure.

Matt

**Comment by alessiovirtuale** [comment]
DId anyone tested it and can tell me how to try to compile in the right way? 
I have some errors during the compilation!
