### ISSUE TITLE
gpgpusim : Aborted (core dumped) 

### ISSUE THREAD

**Issue by yuehs1994** [gpgpu-sim/gpgpu-sim_distribution#92]
I was trying to run the gpgpu-sim_simulation.

When I was trying to run any benmarks, They all appera the same mistake

virtual void shader_core_config::init(): Assertion `toks' failed.
12260 Aborted                 (core dumped)

**Comment by fightforlove** [comment]
what configure file do you use?I change the configure file to the configs/tested-cfgs, this error no longer appears.

**Comment by yuehs1994** [comment]
Thank you, dear fightforlove. A few days ago, I used the same way solved the problem. Still thank you very much for your reply.
