### ISSUE TITLE
How can I change GPGPU-Sim's CUDA compute capability from 5.2 to 7.0

### ISSUE THREAD

**Issue by Sungwoo-Ahn** [gpgpu-sim/gpgpu-sim_distribution#98]
I built the gpgpu-sim 4.0.0 version and used it with CUDA tookkit 9.1 and CUDA SDK.

I successfully executed matrix multiplication in CUDA SDK. 
However, I ran into error with CUDA compute capability when I tried to run "cudaTensorCoreGemm" in CUDA SDK sample application.

It all starts to execute nicely at first, but after loading all ptx configuration releated lines, error comes out like this.
![image](https://user-images.githubusercontent.com/26740096/53476409-ad26bf00-3ab5-11e9-8c2d-7703a622a7f1.png)

I copied configuration files from SM7-Titan V, which should have compute capability 7.0 and it is _shown_ in very first output of execution.
![image](https://user-images.githubusercontent.com/26740096/53476552-fb3bc280-3ab5-11e9-8d63-c62fae582a93.png)

Do I have to change this compute capability number some how by looking inside gpgpu-sim simulator code? Or should I have to find some other way to _link_ this 7.0 capability written in configuration file to simulator?

Thank you for any advice

**Comment by Sungwoo-Ahn** [comment]
I just changed it at gpgpu-sim setup. Any discussions are welcome at any time.

**Comment by zhaojin1997** [comment]
Hello, may I ask how you change the capability? PTX requires sm_19 or less, but I cannot change the capability, so I would like to ask you the following.Thank you.

**Comment by Sungwoo-Ahn** [comment]
@zhaojin1997 I did it by changing gpgpu-dev/libcuda/cuda_runtime_api.cc from 5.2 to 7.0
I'm not sure if this is correct answer, but by running deviceQuery on 1_utilities in CUDA SDK, it seems to work. 
I might be wrong so if you find it, I'm glad to be notified.

**Comment by zhaojin1997** [comment]
Thank you very much for your advice. Your suggestion is very useful because it is the code in "cuda_runtime_apic.cc" that has a problem, not only does it not change the capability logically, but it also removes my PTX Section. However, it is puzzling that I have not changed any of the code. I still need to think about it. Thank you very much for your kind help.

**Comment by Michael-J-K94** [comment]
Hello :)
Does your solution means that changing this part in cuda_runtime_api.cc for older version?
'''
struct _cuda_device_id *GPGPUSim_Init()
{
  static _cuda_device_id *the_device = NULL;
  if( !the_device ) {
    gpgpu_sim *the_gpu = gpgpu_ptx_sim_init_perf();

    cudaDeviceProp *prop = (cudaDeviceProp *) calloc(sizeof(cudaDeviceProp),1);
    snprintf(prop->name,256,"GPGPU-Sim_v%s", g_gpgpusim_version_string );
    prop->major = the_gpu->compute_capability_major();
    prop->minor = the_gpu->compute_capability_minor();
'''

I think the latter part of the last two equation was originally 5 and 2, 
but now has changed to read from the gpgpusim.config.
